/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AsideMenu: typeof import('./components/Layout/components/AsideMenu.vue')['default']
    Dialog: typeof import('./components/Dialog/index.vue')['default']
    Drawer: typeof import('./components/Drawer/index.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    Header: typeof import('./components/Layout/components/Header.vue')['default']
    IEpCheck: typeof import('~icons/ep/check')['default']
    IEpMenu: typeof import('~icons/ep/menu')['default']
    Layout: typeof import('./components/Layout/index.vue')['default']
    PageMain: typeof import('./components/Layout/components/PageMain.vue')['default']
    PageTitle: typeof import('./components/PageTitle/index.vue')['default']
    PopoverOptions: typeof import('./components/PopoverOptions/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UploadDialog: typeof import('./components/UploadDialog/index.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
